### ISSUE TITLE
Pieces cannot be deleted

### ISSUE THREAD

**Issue by projo11** [projo11/groupproject-team-6-alphapro#2]
When building a custom chess board, once the user has placed a piece on the board, it cannot be taken back. To allow the user experience to flow more smoothly, the user should be able to refund a piece purchase in the event that they no longer want that piece. 

To implement this, we will first need to add the functionality describe in my previous issue: a revamp of the shop menu, allowing pieces to be dragged around after being placed on the board. Once this has been accomplished, we need to add a new element to the shop panel. This element will be a trash can, allowing a player to remove the piece from their board in exchange for the points they spent acquiring that piece.

This new shop element will be a GImage object. From there, it should be a simple matter of deleting the piece and receiving points equal to its cost.

**Comment by onzfonz** [comment]
I think this will work 🚀
